name: wx2
channels:
  - auto
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py27_0
  - attrs=19.3.0=py_0
  - automat=0.8.0=py_0
  - bcrypt=3.1.7=py27h7b6447c_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py27_0
  - cffi=1.14.0=py27he30daa8_1
  - chardet=3.0.4=py27_1003
  - colorama=0.4.3=py_0
  - constantly=15.1.0=py27h28b3542_0
  - cryptography=2.8=py27h1ba5d50_0
  - enum34=1.1.6=py27_1
  - hyperlink=19.0.0=py_0
  - idna=2.8=py27_0
  - incremental=17.5.0=py27_0
  - ipaddress=1.0.23=py_0
  - jsonpickle=0.9.6=py27_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=19.3.1=py27_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyhamcrest=1.9.0=py27_2
  - pyopenssl=19.1.0=py27_0
  - pysocks=1.7.1=py27_0
  - python=2.7.18=h15b4118_1
  - queues=0.6.3=py27_0
  - readline=8.0=h7b6447c_0
  - requests=2.22.0=py27_1
  - service_identity=18.1.0=py27h28b3542_0
  - setuptools=44.0.0=py27_0
  - six=1.13.0=py27_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - twisted=19.10.0=py27h7b6447c_0
  - urllib3=1.25.7=py27_0
  - wheel=0.33.6=py27_0
  - zlib=1.2.11=h7b6447c_3
  - zope=1.0=py27_1
  - zope.interface=4.7.1=py27h7b6447c_0
prefix: /home/laurent/anaconda3/envs/wx2

